### ISSUE TITLE
pixi-miniprogram的demo在模拟器可以正常运行，在物理机上运行报错

### ISSUE THREAD

**Issue by ericliyee** [skyfish-qc/pixi-miniprogram#34]
WAServiceMainContext.js:1 MiniProgramError
Intl is not defined
ReferenceError: Intl is not defined
at (libs/pixi.miniprogram.js:1:495696)
at (libs/pixi.miniprogram.js:1:495693)
at C (libs/pixi.miniprogram.js:1:42982)
at createPIXI (pages/index/index.js:22:20)

**Comment by skyfish-qc** [comment]
这个是小程序环境的bug，你可以在微信开发者社区那里找到相同的问题
https://developers.weixin.qq.com/community/develop/doc/00044a6a7782b8f211df8d36e5e400

**Comment by skyfish-qc** [comment]
你可以使用v6版本的，那个版本的pixi没有使用intl这个api

**Comment by ericliyee** [comment]
切换到v6版本报错如下：
TypeError: Cannot read property 'Asset' of undefined
    at vendor.js:formatted:36405
    at installSpine (vendor.js:formatted:57292)
    at Object.<anonymous> (vendor.js:formatted:9571)
    at Function.<anonymous> (WAServiceMainContext.js?t=wechat&s=1711950918874&v=3.2.2:1)
    at :20384/appservice/<SelectorQuery callback function>
    at WAServiceMainContext.js?t=wechat&s=1711950918874&v=3.2.2:1
    at WAServiceMainContext.js?t=wechat&s=1711950918874&v=3.2.2:1
    at Array.forEach (<anonymous>)
    at WAServiceMainContext.js?t=wechat&s=1711950918874&v=3.2.2:1(env: macOS,mp,1.06.2310080; lib: 3.2.2)

**Comment by skyfish-qc** [comment]
6.3.2版本里面的example里面的libs文件夹没有更新到pixi库，请在dist里面复制过去覆盖使用

**Comment by ericliyee** [comment]
问题已解决
